@startuml Database structure

' avoid problems with angled crows feet

entity "User" as user {
    *user_id: string <<generated>>
    --
    firebaseUid: string
    *username: string
    *email: string
    *password: string
    *role: RoleEnum
}

entity "Question" as question {
    *question_id: string <<generated>>
    --
    *title: string
    *description: string
    *difficulty: DifficultyEnum
    *topic: [string]
    *examples: [ { input: string, output: string } ]
    *questionId: number
}

entity "Session" as session {
    *session_id: string <<generated>>
    --
    *participants: [ { userId: string, joinedAt: datetime } ] 
    *questionId: string
    *status: StatusEnum
    *code: string
    *language: LanguageEnum
    *chatHistory: [ { userId: string, username: string, message: text, timestamp: datetime } ]
    *startTime: datetime
    endTime: datetime
}

entity "User Attempt" as userattempt {
    *user_attempt_id: string <<generated>>
    --
    *sessionId: string 
    *userId: string
    *questionId: number
    *submittedBy: string
    *status: boolean
    *code: string
    *language: LanguageEnum
    *testCasesPassed: number
    *totalTestCases: number
    *timeTaken: number
}

' Enums
enum DifficultyEnum {
    Easy
    Medium
    Hard
}

enum StatusEnum {
    Active
    In progress
    Completed
}

enum LanguageEnum {
    Javascript
    Python 
    Java
    C++
}

enum RoleEnum {
    User
    Admin
}

session::_id ||--|{ user::user_id
question::_id ||--o{ session::question_id

' Link fields to enums
user::role -- RoleEnum
question::difficulty -- DifficultyEnum
session::status -- StatusEnum
session::language -- LanguageEnum
userattempt::language -- LanguageEnum

legend right
    == Legend ==
    *field : compulsory / not null
    field : optional / nullable
endlegend

@enduml